name: End-to-end (e2e) Tests

on:
  # Run on all pull requests.
  pull_request:
  push:
    branches:
      - trunk

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: e2e against WordPress latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use desired version of NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Npm install
        run: |
          npm ci
          npm install -g @wordpress/env

      - name: Install WordPress
        run: |
          wp-env start

      - name: Running the tests
        run: |
          $( npm bin )/wp-scripts test-e2e --listTests > ~/.jest-e2e-tests
          $( npm bin )/wp-scripts test-e2e --cacheDirectory="$HOME/.jest-cache"
