name: Lint files

on:
  push:
    branches-ignore:
      - develop
      - staging
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-php:
    name: Lint PHP files
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2.4.0

      - name: Set up PHP
        uses: shivammathur/setup-php@2.21.2
        with:
          coverage: none
          php-version: "8.0"
        env:
          fail-fast: 'true'

      - name: Setup Node
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@f680dac46551dffb2234a240d65ae806c2999dd6 # tag=2.1.0

      - name: Lint files
        run: npm run lint

  lint-search-dev-tools:
    name: Lint Search Dev Tools files
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2.4.0

      - name: Setup Node
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: search/search-dev-tools/package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts
        working-directory: search/search-dev-tools

      - name: Lint files
        run: npm run lint
        working-directory: search/search-dev-tools
