name: Run Tests with Parse.ly

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: "WordPress ${{ matrix.wp }}, multisite: ${{ matrix.multisite }}, Parse.ly: ${{ matrix.parsely }} ${{ matrix.mode }}, PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "7.4"
        wp:
          - "latest"
        multisite:
          - "0"
        parsely:
          - "2.6"
          - "3.1"
          - "3.2"
          - "3.3"
        mode:
          - "filter_enabled"
          - "option_enabled"
        include:
          - php: "7.4"
            wp: "latest"
            multisite: "0"
            parsely: "3.3"
            mode: "filter_and_option_enabled"
    steps:
      - name: Check out source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          submodules: recursive

      - name: Set up PHP
        uses: shivammathur/setup-php@448bd61c6fe9db2113173467e4c22b87ddc2971a # tag=2.18.1
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@f680dac46551dffb2234a240d65ae806c2999dd6 # renovate: tag=2.1.0

      - name: Run tests
        run: |
          ./bin/test.sh \
            --wp ${{ matrix.wp }} \
            --php ${{ matrix.php }} \
            --multisite ${{ matrix.multisite }} \
            --docker-options "-e WPVIP_PARSELY_INTEGRATION_PLUGIN_VERSION=${{ matrix.parsely }} -e WPVIP_PARSELY_INTEGRATION_TEST_MODE=${{ matrix.mode }}" \
            --order-by=random
