name: release-changelog

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  tag-release:
    name: Tag Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.id-generator.outputs.id }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813 # tag=v1.4.3
        with:
          egress-policy: audit

      - name: Check out source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Retrieve tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Get tag name
        id: id-generator
        run: |
          current_date=$(date '+v%Y%m%d.')
          minor_version=0
          tag=$(git tag -l "${current_date}*" --sort=-version:refname | head -n 1)
          if [ -n "${tag}" ]; then
              minor_version=$(echo "${tag}" | awk -F. '{print $2+1}')
          fi

          echo "::set-output name=id::${current_date}${minor_version}"

      - name: Tag release
        run: git tag ${{ steps.id-generator.outputs.id }}

      - name: Push tags
        run: git push --tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # renovate: tag=v0.1.14
        with:
          generate_release_notes: true
          tag_name: ${{ steps.id-generator.outputs.id }}

  release-changelog:
    name: Publish Changelog
    runs-on: ubuntu-latest
    needs: tag-release
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813 # tag=v1.4.3
        with:
          egress-policy: audit

      - name: Check out source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Set up Node.js environment
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3.3.0
        with:
          node-version: 14
          cache: npm

      - name: Install dependencies
        working-directory: ./bin
        run: npm ci

      - name: Promote changelog entries
        env:
          CHANGELOG_BEARER_TOKEN: ${{ secrets.CHANGELOG_BEARER_TOKEN }}
          RELEASE_ID: ${{ needs.tag-release.outputs.id }}
        working-directory: ./bin
        run: node ./mark-production-changelog.js
